# Generated by Django 3.0.6 on 2020-07-14 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocommentitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocommentitem',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.VideoItem'),
        ),
        migrations.AddField(
            model_name='songitem',
            name='app_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.AppItem'),
        ),
        migrations.AddField(
            model_name='songitem',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Album'),
        ),
        migrations.AddField(
            model_name='podcastitem',
            name='app_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.AppItem'),
        ),
        migrations.AddField(
            model_name='podcastitem',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='app_item',
            field=models.ManyToManyField(to='home.AppItem'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featured',
            name='app_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.AppItem'),
        ),
        migrations.AddField(
            model_name='blogitem',
            name='app_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.AppItem'),
        ),
        migrations.AddField(
            model_name='blogitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcommentitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcommentitem',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BlogItem'),
        ),
    ]
