# Generated by Django 3.0.6 on 2020-07-18 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200714_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogitem',
            name='app_item',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='app_item',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='app_item',
        ),
        migrations.RemoveField(
            model_name='podcastitem',
            name='app_item',
        ),
        migrations.RemoveField(
            model_name='songitem',
            name='app_item',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='app_item',
        ),
        migrations.AddField(
            model_name='blogitem',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='featured',
            name='item_type',
            field=models.CharField(choices=[('blog', 'blog'), ('podcast', 'podcast'), ('video', 'video'), ('songs', 'song')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='playlist',
            name='blog_items',
            field=models.ManyToManyField(to='home.BlogItem'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='item_type',
            field=models.CharField(choices=[('blog', 'blog'), ('podcast', 'podcast'), ('video', 'video'), ('songs', 'song')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='playlist',
            name='padcast_items',
            field=models.ManyToManyField(to='home.PodcastItem'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_items',
            field=models.ManyToManyField(to='home.SongItem'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='vidoe_items',
            field=models.ManyToManyField(to='home.VideoItem'),
        ),
        migrations.AddField(
            model_name='podcastitem',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='songitem',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='category',
            field=models.CharField(choices=[('movie', 'movie'), ('program', 'program'), ('sermon', 'sermon'), ('production', 'production')], max_length=10),
        ),
        migrations.DeleteModel(
            name='AppItem',
        ),
    ]
