# Generated by Django 3.0.6 on 2020-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200718_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='item_type',
            field=models.CharField(choices=[('blog', 'blog'), ('video', 'video'), ('songs', 'song'), ('podcast', 'podcast')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='item_type',
            field=models.CharField(choices=[('blog', 'blog'), ('video', 'video'), ('songs', 'song'), ('podcast', 'podcast')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='song'),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='category',
            field=models.CharField(choices=[('production', 'production'), ('movie', 'movie'), ('sermon', 'sermon'), ('program', 'program')], max_length=10),
        ),
    ]
