# Generated by Django 3.0.6 on 2020-07-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200718_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='item_type',
            field=models.CharField(choices=[('songs', 'song'), ('podcast', 'podcast'), ('video', 'video'), ('blog', 'blog')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='item_type',
            field=models.CharField(choices=[('songs', 'song'), ('podcast', 'podcast'), ('video', 'video'), ('blog', 'blog')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='uploaded_file',
            field=models.FileField(blank=True, default='default art.png', null=True, upload_to='song'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='category',
            field=models.CharField(choices=[('movie', 'movie'), ('program', 'program'), ('sermon', 'sermon'), ('production', 'production')], max_length=10),
        ),
    ]
