# Generated by Django 3.0.6 on 2020-07-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200718_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='item_type',
            field=models.CharField(choices=[('podcast', 'podcast'), ('songs', 'song'), ('blog', 'blog'), ('video', 'video')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='item_type',
            field=models.CharField(choices=[('podcast', 'podcast'), ('songs', 'song'), ('blog', 'blog'), ('video', 'video')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='album_art',
            field=models.FileField(blank=True, default='default art.png', null=True, upload_to='album art'),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='song'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='category',
            field=models.CharField(choices=[('movie', 'movie'), ('sermon', 'sermon'), ('program', 'program'), ('production', 'production')], max_length=10),
        ),
    ]
