# Generated by Django 3.0.6 on 2020-08-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200718_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='vidoe_items',
            new_name='video_items',
        ),
        migrations.AddField(
            model_name='playlist',
            name='chart',
            field=models.CharField(choices=[('mood', 'mood'), ('weekly', 'weekly')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='featured',
            name='item_type',
            field=models.CharField(choices=[('blog', 'blog'), ('songs', 'song'), ('podcast', 'podcast'), ('video', 'video')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='item_type',
            field=models.CharField(choices=[('blog', 'blog'), ('songs', 'songs'), ('podcast', 'podcast'), ('video', 'video')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='category',
            field=models.CharField(choices=[('production', 'production'), ('sermon', 'sermon'), ('movie', 'movie'), ('program', 'program')], max_length=10),
        ),
    ]
