# Generated by Django 3.0.6 on 2020-08-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200802_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='item_type',
            field=models.CharField(choices=[('video', 'video'), ('songs', 'song'), ('podcast', 'podcast'), ('blog', 'blog')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='blog_items',
            field=models.ManyToManyField(blank=True, to='home.BlogItem'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='chart',
            field=models.CharField(choices=[('weekly', 'weekly'), ('mood', 'mood')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='item_type',
            field=models.CharField(choices=[('video', 'video'), ('songs', 'songs'), ('blog', 'blog'), ('podcast', 'podcast')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='padcast_items',
            field=models.ManyToManyField(blank=True, to='home.PodcastItem'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song_items',
            field=models.ManyToManyField(blank=True, to='home.SongItem'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='video_items',
            field=models.ManyToManyField(blank=True, to='home.VideoItem'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='category',
            field=models.CharField(choices=[('movie', 'movie'), ('program', 'program'), ('sermon', 'sermon'), ('production', 'production')], max_length=10),
        ),
    ]
